### ISSUE TITLE
How to load more than 5 image target

### ISSUE THREAD

**Issue by lovisio** [8thwall/web#104]
Hello,
I try since two weeks to add more than 5 image target automatic. I can't find any information or code example about it. The only line on the doc is this one 
XR.XrController.configure({imageTargets: ['image-target1', 'image-target2', 'image-target3']})

Could you explain me how to make it work ? In fact I have 6 image to target... So only one that don't work for the moment.

Thanks a lot.

**Comment by lovisio** [comment]
Find a solution , in my case I add to call           XR8.XrController.configure({imageTargets: ['videotarget1']}) and not XR. Working now

**Comment by atomarch** [comment]
If SLAM is enabled, the maximum number of image targets that can be actively looked for is 5.  If you have an image-target only experience, you can disable SLAM (e.g. disableWorldTracking=true) and that raises the limit to 10.  Please see https://www.8thwall.com/docs/web/#image-target-quantities
