### ISSUE TITLE
8i-hologram example not working on iOS (Safari) or Android (Chrome)

### ISSUE THREAD

**Issue by marksteelz3** [8thwall/web#106]
I'm not sure what the cause of the error is, but when try to load the 8i-hologram example I get an "Oops, something went wrong!" error message. This happens on both iOS (Safari) and Android (Chrome). I'm wondering if this is just happening for me (possibly some network issue) or if other people have also encountered this error.

**Comment by atomarch** [comment]
Hi @marksteelz3 , 8i changed things on their CDN a while back, resulting in broken links to their libraries which caused these errors.  The source code for this GitHub project contained all of the correct code/links, but the hosted demo was outdated.  I have recently updated the QR code and URL to an updated live demo.  Check out https://templates.8thwall.app/hologram-8i-threejs
