### ISSUE TITLE
Multi-camera smartphones choice the regular lens

### ISSUE THREAD

**Issue by jamess922** [8thwall/web#108]
I have a phone with multiple rear cameras，and try with the demo it's  use the  wrong lens ，like a telescope lens，my phone is HUAWEI mate 20pro it‘’s use the 3x lens.
So is that possible to select the regular lens  ?

**Comment by atomarch** [comment]
Hi @jamess922 are you seeing this on all demos, or just a specific one?  In our most recent 13.1 release, we specifically added fixes for the Huawei Mate 20 Pro (model LYA-L09) and Huawei P20 Pro so they would select the correct camera.  Check your project settings -> engine version to make sure you aren't locked to an older engine version.

If that doesn't help, I wonder if your phone is returning a different model number or user-agent string.  Can you please collect the following info from your device?

- Browse to https://webrtc.github.io/samples/src/content/devices/input-output/ and note the list of cameras detected

- http://faisalman.github.io/ua-parser-js/ and collect the User-agent string for your browser.  It will say "Result for XXXXXXXXXX (User-Agent string of your browser)"

Thanks!

**Comment by jamess922** [comment]
Yes  i tried all the a-frame demos and they were all working with worry lens
and here is the info from my Huaweimate 20 pro
![001](https://user-images.githubusercontent.com/28625879/70104746-f675f180-1679-11ea-86bc-cdd13d0543e0.jpg)
![002](https://user-images.githubusercontent.com/28625879/70104752-faa20f00-1679-11ea-8b37-3efb7b3b3082.jpg)

**Comment by atomarch** [comment]
Interesting, it looks as if the Mate 20 Pro has 6 different models numbers.  Check out https://www.phonemore.com/models/huawei/mate-20-pro/

On these devices getUserMedia by default returns the telephoto camera.  We can override this on our end for specific phones like this.  We'll implement the same workaronud for these additional Mate 20 Pro model numbers.  Thanks for providing this info.

**Comment by atomarch** [comment]
Closing old ticket.  This was resolved in late-2019 and engine was updated early 2020 to include this fix.

https://github.com/8thwall/ua-parser-js/commit/b45bd07bab830415b403e4755c8e0f1bd8234883
