### ISSUE TITLE
Flyer demo not tracking target image

### ISSUE THREAD

**Issue by AkashNan** [8thwall/web#109]
I have set up flyer demo but it's not tracking target image. I have replaced app key properly as well uploaded target image on 8th wall. While uploading image target on 8th wall, I did not see save and enable option only save is there.

Could you please help. Details of issue can be found below

> https://stackoverflow.com/questions/59169987/8th-wall-image-target-not-tracking-image

**Comment by atomarch** [comment]
Closing as this was resolved in the StackOverflow thread.
