### ISSUE TITLE
src folder missing..?

### ISSUE THREAD

**Issue by ChiefBreakeverything** [8thwall/web#111]
Hey team,

I ran into a strange issue when deploying the tutorial found [here](https://www.8thwall.com/quick-start-web).

Specifically I get the following issue when I go to serve:

`PS C:\Dev\Web\EightWallExampleProject\web-master> serve\bin\serve.bat -d gettingstarted\xraframe
8888888888888888888888888888888888888888888888888888888888888888
8
8  ""C:\Dev\Web\EightWallExampleProject\web-master\serve\bin\serve.bat"" [options]
8  -d DIR    path to serve [required]
8  -p PORT   default PORT=8080
8  -h        hot reload on localhost
8  -r        enable hot reload
8  -i IFACE  choose network interface
8  -n        don't print these instructions
8
8888888888888888888888888888888888888888888888888888888888888888
ECHO is off.
The filename, directory name, or volume label syntax is incorrect.
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module 'C:\Dev\Web\EightWallExampleProject\web-master\src\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:785:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)[39m
[90m    at internal/main/run_main_module.js:16:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}`

It looks like it wants a .js file that isn't in the expected src/ folder? Sorry if this is a dumb question!

**Comment by atomarch** [comment]
Hello @ChiefBreakeverything , did you download/clone the entire GitHub repo? Prior to running the "serve" command did you run "npm install" from inside the serve\ directory?

Also, you'll need to run these commands using the standard command prompt (cmd.exe), not PowerShell...

**Comment by ChiefBreakeverything** [comment]
I ran npm install beforehand, and it seemed to have completed successfully.

The problem was indeed using PowerShell, standard command prompt worked just fine. Thanks!
