### ISSUE TITLE
OrbitControls using ThreeJS

### ISSUE THREAD

**Issue by ArfaouiHamouda** [8thwall/web#115]
Hi , i have been working with 8th wall + ThreeJS to Render ( VIDEOS, IMAGES, 3D Objects ), I was trying to apply OrbitControls from ThreeJS docs into 8th Wall Code but I was unable to do that as of 8th Wall do a lot of Job internally, I want to know if it's possible to do that and put me on the right track .
PS : my Code looks similar to the ThreeJS Example of Placeholder on your Repo .

Thanks in advance

**Comment by atomarch** [comment]
Hello @ArfaouiHamouda , what are you trying to accomplish?  8th Wall controls the position/rotation of the three.js camera as you move your phone around in the real world.  OrbitControls allows the camera to orbit around a target, so these two things aren't going to play nicely together.  If you are looking to move/rotate/scale the scene content itself, you'll want to do this on your scene content and not the camera.

**Comment by ArfaouiHamouda** [comment]
i am trying to achieve the manipulation only Zoom in/out and Change View (Camera Angle) of the augmented objects using Touch Controle, far as i know you can achieve that with OrbitControls . i guess this is more clear.

**Comment by luigimannoni** [comment]
@ArfaouiHamouda probably it's better if you rotate/scale the model/scene itself tracking the finger on the screen rather than using Three's OrbitControls
