### ISSUE TITLE
device not authorized to view ios 13

### ISSUE THREAD

**Issue by danhtanhd** [8thwall/web#118]
I have problems showing my example through IOS 12.2 and 13.3.1
When the device displays, it receives the message "device not authorized to view". Although I have javacripts cookies enabled and camera and microphone access is not successful. With Android devices there is no problem.

**Comment by atomarch** [comment]
iOS Safari has a feature called Intelligent Tracking Prevention that can block third party cookies (what we use to authorize your device while you're developing). When they get blocked, we can't verify your device.

Please see https://www.8thwall.com/docs/web/#device-not-authorized for steps to fix.
