### ISSUE TITLE
xrimagefound not emiting

### ISSUE THREAD

**Issue by yugich** [8thwall/web#127]
I trying run Alpha Video example, but events xrimagefound not emitting and not found the tracking.
I using a default outside.jpg and default features from example
Does anyone have a suggestion?

**Comment by atomarch** [comment]
Is your image target configured to "**load automatically**"?  On the image target library page, edit your image target.  You can find this checkbox towards the bottom of the page.

If it's not set to load automatically, you'll need to call `XR8.XrController.configure()` to load the desired image target.

See https://www.8thwall.com/docs/web/#changing-active-image-targets

**Comment by yugich** [comment]
Now working, sorry for this very simple question... Sometimes is a simple thing to generate headache
