### ISSUE TITLE
Three.js examples don't work

### ISSUE THREAD

**Issue by HectorArellano** [8thwall/web#135]
When trying to work with Three.js demos I get the "Oops, something went wrong!" message, testing on Safari using an Iphone 7 with software version 13.3.1. The A-Frame demos do work correctly, but none of the ones using Three.js as a rendering platform.

**Comment by atomarch** [comment]
Any errors displayed if you connect your iPhone via USB and fire up the Safari debugger?

I just tested https://github.com/8thwall/web/tree/master/examples/threejs/placeground and it's working for me. Added my app key to https://github.com/8thwall/web/blob/master/examples/threejs/placeground/index.html#L22 (replacing the XXXX's), ran the serve script locally, and connected my phone.

Tested successfully on:
- iPhone 6, iOS 12.1
- IPhone X, iOS 13.5.1
- iPhone XS Max, iOS 13.5.1
- iPhone SE (2020), iOS 13.4.1
- iPad 5th Gen (2017), iOS 13.4.1

**Comment by atomarch** [comment]
I also just tested various threejs demos at https://www.8thwall.com/8thwall, also working.  Might want to completely quit safari, reboot the device, etc see if that helps.  Best would be to look at the actual safari logs.

**Comment by HectorArellano** [comment]
Safari's logs only display the following:
![Screenshot 2020-07-30 at 19 15 44](https://user-images.githubusercontent.com/13965114/88953343-160cfa80-d299-11ea-894c-2d3fd65c5870.png)

**Comment by HectorArellano** [comment]
Closed Safari, restarted the device and the issue keeps appearing with the Three.js examples. Wonder why the A-Frame ones work but the Three.js don't.
