### ISSUE TITLE
a-entity attribute position not work for gltf-model

### ISSUE THREAD

**Issue by phanhongphucit** [8thwall/web#138]
Hi,

I have an image recognization and would like to change the position of 3D model relative to the image. But the following code with attribute position does not work:
```
<a-entity xrextras-named-image-target="name: fox">
    <!-- Add a child entity that can be rotated independently of the image target. -->
    <a-entity xrextras-one-finger-rotate gltf-model="#mech_drone_glb" position="-100 100 0"></a-entity>
</a-entity>

```
Could you please help?
Thank you

**Comment by atomarch** [comment]
You are setting a very large position offset from the image target.  The model is likely just very far away and therefore you don't see it in view.  Prove this to yourself by setting a much smaller position offset.

Original:

```
  <a-entity xrextras-named-image-target="name: model-target">
    <!-- Add a child entity that can be rotated independently of the image target. -->
    <a-entity xrextras-one-finger-rotate gltf-model="#jelly-glb"></a-entity>
  </a-entity>
```

Result:
![no-offset](https://user-images.githubusercontent.com/5042980/91084605-1d59c680-e601-11ea-919a-6b36bea8d4f4.jpg)


With offset:

```
  <a-entity xrextras-named-image-target="name: model-target">
    <!-- Add a child entity that can be rotated independently of the image target. -->
    <a-entity position="0.5 0.5 0"xrextras-one-finger-rotate gltf-model="#jelly-glb"></a-entity>
  </a-entity>
```

Result:
![with-offset](https://user-images.githubusercontent.com/5042980/91084619-22b71100-e601-11ea-9c39-8f04e3f5ec9a.jpg)
