### ISSUE TITLE
Handling Events With JavaScript

### ISSUE THREAD

**Issue by dhaiduk** [8thwall/web#145]
It is possible to implement event handling as it is done in a-frame? In my opinion, is it does not work in 8thwall

<script>
  AFRAME.registerComponent('change-color-on-hover', {
    schema: {
      color: {default: 'red'}
    },

    init: function () {
      var data = this.data;
      var el = this.el;  // <a-box>
      var defaultColor = el.getAttribute('material').color;

      el.addEventListener('mouseenter', function () {
        el.setAttribute('color', data.color);
      });

      el.addEventListener('mouseleave', function () {
        el.setAttribute('color', defaultColor);
      });
    }
  });
</script>
<body>
  <a-scene>
    <a-box color="#EF2D5E" position="0 1 -4" change-color-on-hover="color: blue"></a-box>

    <a-camera><a-cursor></a-cursor></a-camera>
  </a-scene>
</body>

**Comment by atomarch** [comment]
Yes, here are some examples:

https://www.8thwall.com/8thwall/placeground-aframe/master/tap-place.js#L6

https://www.8thwall.com/8thwall/tossobject-aframe/master/toss-object.js#L6
