### ISSUE TITLE
Glass Animals QR redirect results in 404

### ISSUE THREAD

**Issue by Cplacke** [8thwall/web#153]
Hello so I recent have revived a poster from a virtual concert and I was excited to scan the QR attached 

but it redirects to a 404 not found page
can we add the right url redirect

https://apps.8thwall.com/cznwixyn/livelivelive/
![image](https://user-images.githubusercontent.com/14809822/104667252-a43c3800-56a3-11eb-9c04-2040f8ec296d.jpeg)
![image](https://user-images.githubusercontent.com/14809822/104667262-ab634600-56a3-11eb-845b-460673e65a5f.jpeg)

Fixing these posters would be very appreciated, I will also try to learn your codebase and perhaps try and contribute to this

**Comment by atomarch** [comment]
Hello, you'll need to reach out to the band directly.  This was a project within their account that they have since taken down.

**Comment by Cplacke** [comment]
I appreciate the information, thank you Tony
