### ISSUE TITLE
Android is not working on ThreeJS apps

### ISSUE THREAD

**Issue by jalamprea** [8thwall/web#157]
Testing 8th wall apps using aframe works properly on android, but the applications using directly ThreeJS are not working on android.
None of these examples work on Android, only on iPhone: https://github.com/8thwall/web/tree/master/examples/threejs
Aframe examples work properly on both Andriod and iPhone: https://github.com/8thwall/web/tree/master/examples/aframe

**Comment by atomarch** [comment]
I just tested https://github.com/8thwall/web/tree/master/examples/threejs/placeground (code as-is, simply replaced the X’s in https://github.com/8thwall/web/blob/master/examples/threejs/placeground/index.html#L22 with my own unique appKey, and successfully ran these demos on the following devices, served using a webserver running locally on my laptop:
- Huawei P30 Pro
- Samsung Galaxy S21 5G
- Samsung Galaxy S9 Plus
