### ISSUE TITLE
404 error page from three.js flyer example

### ISSUE THREAD

**Issue by ybinstock** [8thwall/web#159]
On https://github.com/8thwall/web/blob/master/examples/threejs/flyer/index.html

line 18, there is

  

That link leads to a 404 page. 

That issue may not just be on the three.js/flyer example page, but on others as well. 

The current URL should be https://github.com/8thwall/web/tree/master/xrextras

**Comment by atomarch** [comment]
Thanks for the heads up.  Looks like the incorrect link exists in lots of other files as well.
