### ISSUE TITLE
Playcanvas Shadow Material Generation Fail

### ISSUE THREAD

**Issue by spencer-evans-pnt** [8thwall/web#168]
With the new Playcanvas engine [release 1.42.0](https://github.com/playcanvas/engine/releases/tag/v1.42.0), support for shadow coordinates generation in VS was removed. This has broken the shadow material generation [in xrextras Playcanvas](https://github.com/8thwall/web/blob/master/xrextras/src/playcanvas/playcanvas.js#L13).

`Error in material "XR Shadow Material" with flags 65548`
`ERROR: Undefined function 'getShadowPCF3x3VS()' used in the following call chain:getEmission`

This error is occurring in the latest [AR World Tracking Starter Kit project](https://playcanvas.com/project/631719/overview/ar-world-tracking-starter-kit).

**Comment by atomarch** [comment]
Thanks for linking your fix.  I've tested it against a handful of various PlayCanvas engine versions to make sure it's backwards compatible, and everything seems fine:

- 1.42.0
- 1.41.2
- 1.41.0
- 1.40.0
- 1.38.1
- 1.35.0

**Comment by atomarch** [comment]
@spencer-evans-pnt FYI, this fix is now live on CDN
