### ISSUE TITLE
World tracking broken for ThreeJS based solutions running on iOS15

### ISSUE THREAD

**Issue by jimib** [8thwall/web#180]
This project works as expected on iOS14 but not on iOS15:
https://www.8thwall.com/8thwall/placeground-threejs

In both cases the modal asking for access to motion sensors appear, but on iOS15 there is significant drift, nothing sticks to the floor.

On iOS15, orientation/rotation of the phone is correctly detected and the placed trees rotate away, but moving left/right/forward/backwards has no effect at all.

The equivalent A-Frame project works fine on both iOS14 and iOS15: 
https://www.8thwall.com/8thwall/placeground-aframe

It appears to be exclusive to ThreeJS in combination with iOS15. All my existing projects are currently broken and migrating to a-frame is too much work. I'm keen to help in any way I can to resolve this issue if that's through additional testing or providing logs.

**Comment by jparismorgan** [comment]
Hi @jimib, thanks for filing the issue. This is a known bug with how our engine handles iOS 15 + WebGL 2. We're currently working on a fix, but in the meantime you can disable WebGL 2 like so:
``` 
XR8.run({canvas: document.getElementById('camerafeed'), webgl2: false})
```

**Comment by jimib** [comment]
Thank you @jparismorgan - that worked perfectly. Such a relief.
