### ISSUE TITLE
iOS15.1 Safari - doesn't show camera and World Tracking broken

### ISSUE THREAD

**Issue by jimib** [8thwall/web#186]
This is currently a developer preview of iOS15.1 and isn't available to the public.

Even the official 8th Wall WebAR demo is broken by this iOS update:

https://8thwall.8thwall.app/configurator-aframe/

![IMG_B76508A23C64-1](https://user-images.githubusercontent.com/468140/135603203-d9da3d81-bcce-43d6-8b2e-478bfa13979d.jpeg)

**Comment by atomarch** [comment]
iOS 15.1 has not been released yet and is currently in beta.  There are a number of known Safari regressions that Apple is currently working on.  The one specifically related to this issue (which affects more than just 8th Wall) is https://bugs.webkit.org/show_bug.cgi?id=230617


The latest from [Apple](https://bugs.webkit.org/show_bug.cgi?id=230617#c11) is: “I believe this will be part of Beta 3”

**Comment by jimib** [comment]
Very good, I just wanted to be sure 8th Wall were aware of it. Thank you.
