### ISSUE TITLE
Github project behind builds on 8th Wall servers

### ISSUE THREAD

**Issue by ephb** [8thwall/web#194]
When building the is project from source, notably xrextras, some components seems to be missing that are used in the official examples.

I noticed this with `xrextras-opaque-background` but and `lifecycle` but there might be others.

**Comment by atomarch** [comment]
Good catch, thanks for bringing this to our attention.  Just updated to reflect the current version on CDN

https://github.com/8thwall/web/commit/660ee8b0a1a5925ba59526ec4318032a4225fd17#diff-4dcebeeec882a3a56812f7e6e92c3f1bc3a2f927e0277b9928ba851ff0bf62f1

**Comment by ephb** [comment]
Thanks @atomarch for taking care of this
