### ISSUE TITLE
Custom xrextras-named-image-target not working or outdated

### ISSUE THREAD

**Issue by Mickellg** [8thwall/web#230]
Trying to make a custom component to be able to use in my a-scene using the code in the file found in the repo. The file is also used in the video below. Component never initializes even though it is registered and imported/exported properly.

https://www.youtube.com/watch?v=VwQk4msRPs4&t=961s

**Comment by dattanchu** [comment]
It should still be working. I suggest hanging out on https://www.8thwall.com/slack which should have better response from the community and official support engineers on this matter. Make sure to include what code you have tried so you can get better suggestions.

**Comment by Mickellg** [comment]
Thanks!!! I am, I just thought I might get a quicker response here.
