### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by Kumaresh-Rajalingam** [8thwall/web#30]
when I try to run **'npm start'** its throwing error

ERROR in ./src/app.js
**Module not found: Error: Can't resolve './sumerian-exports' in 'D:\Kumaresh\web-master (2)\web-master\gettingstarted\xrsumerian\src'
 @ ./src/app.js 7:0-46 18:21-33**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amplify-js-app@1.0.0 start: `webpack && pushd serve && npm install && popd && ./serve/serve -d dist -n`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the amplify-js-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anurag\AppData\Roaming\npm-cache\_logs\2018-12-28T15_32_38_443Z-debug.log

solution thanks in advance!

**Comment by mralbean** [comment]
Hi!

This error is saying that a `sumerian-exports` file does not exist within the src directory of your project. Did you make sure to download and place this file in the correct location when publishing your Sumerian scene? 

https://github.com/8thwall/web/tree/master/gettingstarted/xrsumerian#publishing-a-sumerian-scene

**Comment by mralbean** [comment]
It looks like this was resolved through a conversation in the #help-and-support channel on our [slack](https://8thwalldevs.slack.com).  The `sumerian-exports.json` file was missing.

Closing this issue out.
