### ISSUE TITLE
How to track an image (not QR) and display a 3D object on that?

### ISSUE THREAD

**Issue by lim-anggun** [8thwall/web#52]
Hello,
I am new to 8th Wall and I want to **track an image and display a object 3D on top of it**. How can I achieve this? Thanks in advance.

**Comment by p2lem8dev** [comment]
Hello,
I think that AR.js may be useful for that. It allows to track specific images and render entities on them. But there're many quastions.
I tried to use these frameworks together and didn't get any good results.

**Comment by p2lem8dev** [comment]
I think [this could help](https://github.com/8thwall/web/tree/master/gettingstarted/xraframe-imagetarget)
If not (I didn't test it) try to use [AR.js](https://github.com/jeromeetienne/AR.js)

**Comment by atomarch** [comment]
Good news, image detection/tracking was just launched into our Beta channel yesterday as part of our upcoming R11 release.  Full documentation and examples will be ready as part of the official launch. For now, here are some resources to help you get started:

- Getting Started Guide: https://8thwalldevs.slack.com/archives/CB4FPH90A/p1554867191075400
- 8th Wall Web: Image targets beta demo video: https://www.youtube.com/watch?v=WjwyBLBhfXU
- Example A-Frame / three.js projects: https://github.com/8thwall/web/tree/master/gettingstarted
