### ISSUE TITLE
Not able to connect to local serve from phone

### ISSUE THREAD

**Issue by ccasad** [8thwall/web#64]
Hi, I'm trying to get the quick start app working so that I can serve it locally, using the quick start guide https://console.8thwall.com/quick-start-web. I've got the project building and have tried using en0 and en4 as the network interface. I went into my phone's Safari browser and it says that the device is authorized (I authorized it via qr code as well as I logged into my 8thwall console via my phone's Safari browser). But every time I go to the address with the port (https://192.168.0.203:8082) it shows the popup saying "Device Not Authorized to View https://192.168.0.203. 

Not sure what else to do? Am I missing something?

Thanks

**Comment by atomarch** [comment]
Are you in private browsing mode?  If so, might try leaving private browsing mode, re-authorize your device, and try again.  If you browse to https://apps.8thwall.com directly from your device, it will display its authorization status.

**Comment by ccasad** [comment]
I think it was the private browsing mode. Works now, thanks.
