### ISSUE TITLE
Autoplace objects

### ISSUE THREAD

**Issue by wajdibr** [8thwall/web#65]
Hello,
Thank you for this web sdk. I have a simple question. While trying the getting started example with aframe, I'm trying to "automatically place" an object, when recognizing first time a flat surface.
Do you have an idea about how this could be done using 8thwall sdk ?
Thank you!

**Comment by atomarch** [comment]
Hello @wajdibr , Yes this can be done.  8th Wall Web provides instant surfaces.  Simply place your object such that the base sits at a height of Y=0 and it will appear on whatever surface is in front of you with the experience starts.  All of our "gettingstarted" examples do this - check out https://github.com/8thwall/web/tree/master/gettingstarted

**Comment by wajdibr** [comment]
@atomarch thank you, however which event should be fired to achieve this ?
JS onload is not working for the sample placeground in threejs,

Thank you

**Comment by atomarch** [comment]
What exactly is not working for you, and do you have any error messages?  In the threejs/placeground example, objects are placed when you tap the screen.  The code is raycasting against an invisible "surface" (plane) object at Y=0, and the trees are placed at the touch point (x,0,z).  There is a tap listener: https://github.com/8thwall/web/blob/master/examples/threejs/placeground/index.js#L111

**Comment by wajdibr** [comment]
No actually it's working,
What i'm trying to achieve is to place objects onload, not ontap. I would like that, my own scene in 8th wall would place the tree without raycasting ^^
And sorry, i'm really new to 8th wall sdk :)

**Comment by atomarch** [comment]
I understand.  There is nothing "special" you need to do here then :) Simply place objects in your (A-Frame, three.js, etc) scene and when things load they will "automatically" be visible when the experience loads.  Our gettingstarted examples all do this, no tap required.  Check out: https://github.com/8thwall/web/tree/master/gettingstarted

**Comment by wajdibr** [comment]
Thank you very much, i thought it will be some math tricks to have ^^'
Thank you for your quick and precise answers :)

**Comment by atomarch** [comment]
No math tricks :) Simply place the content in your scene.  If you want the object to live on the surface, just make sure that the bottom of the 3d model sits at a height of Y=0.
